### ISSUE TITLE
How to run the simulation

### ISSUE THREAD

**Issue by ly58** [arrival-ltd/catalyst-rl-tutorial#1]
How to run the simulation. The documentation does not mention how to run, nor does it mention the version of each library. 
![Screenshot from 2020-10-21 14-37-56](https://user-images.githubusercontent.com/71643334/96682266-253ca980-13ab-11eb-9898-3e58049ecb1e.png)

**Comment by dtransposed** [comment]
This is a well-known issue, which happens when you install PyRep in the incorrect way.
Please follow the instruction here: https://github.com/stepjam/PyRep
Make sure that PyRep **is installed inside your virtual environment** (catalystenv).
Also, note that PyRep may not be working properly with MacOS. It has been tested on Ubuntu an Windows.
